# 프론트엔드 어플리케이션 설정
image:
  repository: 183631327456.dkr.ecr.ap-northeast-2.amazonaws.com/3tier-ecr-frontend
  tag: frontend_v1.0_20250323
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: frontend.example.com

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

environment: dev