# 프론트엔드 어플리케이션 설정
image:
  repository: 183631327456.dkr.ecr.ap-northeast-2.amazonaws.com/tier3-frontend
  tag: frontend_v1.0_20250325052736
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: tier3-frontend-lb  # 로드밸런서 이름 지정
  host: mydairy.my


resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

environment: dev
