# 프론트엔드 어플리케이션 설정
image:
  repository: 183631327456.dkr.ecr.ap-northeast-2.amazonaws.com/tier3-frontend
  tag: frontend_v1.0_20250325052736
  pullPolicy: Always

replicaCount: 1

# HPA 설정 추가
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: tier3-frontend-lb
    # External DNS 어노테이션 추가
    external-dns.alpha.kubernetes.io/hostname: mydairy.my,www.mydairy.my
  hosts:
    - host: mydairy.my
      paths:
        - path: /
          pathType: Prefix
    - host: www.mydairy.my
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

environment: dev
