apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
    path: charts/frontend
    helm:
      values: |
        image:
          repository: {{ .Values.global.repositories.frontend }}
          tag: latest
        
        ingress:
          enabled: true
          hosts:
            - host: {{ .Values.global.domain }}
              paths:
                - path: /
                  pathType: Prefix
            - host: www.{{ .Values.global.domain }}
              paths:
                - path: /
                  pathType: Prefix
        
        environment: {{ .Values.global.environment }}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true