apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    env: {{ .Values.environment }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        # 이 주석이 변경될 때마다 Pod가 재시작됩니다
        kubectl.kubernetes.io/restartedAt: {{ now | quote }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # 환경 변수 추가 - 내부 통신용 백엔드 URL
          env:
            # 브라우저에서 사용할 백엔드 URL (외부 접근용)
            - name: REACT_APP_API_URL
              value: {{ .Values.backendService.externalUrl | default (printf "https://api.%s" .Values.global.domain) | quote }}
            # 서버 사이드 렌더링이나 내부 통신용 백엔드 URL (내부 접근용)
            - name: BACKEND_SERVICE_URL
              value: {{ .Values.backendService.internalUrl | quote }}